# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/epi/PycharmProjects/GRASS-Server/UI/GrassWidget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.2.dev1804051511
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(378, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setMaximumSize(QtCore.QSize(40, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/resources/icons/Grass_GIS.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.commanddescription = QtWidgets.QLabel(self.groupBox_2)
        self.commanddescription.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.commanddescription.setText("")
        self.commanddescription.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commanddescription.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.commanddescription.setObjectName("commanddescription")
        self.horizontalLayout_2.addWidget(self.commanddescription)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 354, 118))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.commandtab = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandtab.sizePolicy().hasHeightForWidth())
        self.commandtab.setSizePolicy(sizePolicy)
        self.commandtab.setMinimumSize(QtCore.QSize(0, 100))
        self.commandtab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.commandtab.setObjectName("commandtab")
        self.CommandOutput = QtWidgets.QWidget()
        self.CommandOutput.setObjectName("CommandOutput")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.CommandOutput)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.commandoutput = QtWidgets.QTextEdit(self.CommandOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commandoutput.sizePolicy().hasHeightForWidth())
        self.commandoutput.setSizePolicy(sizePolicy)
        self.commandoutput.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.commandoutput.setObjectName("commandoutput")
        self.verticalLayout_2.addWidget(self.commandoutput)
        self.commandtab.addTab(self.CommandOutput, "")
        self.Manual = QtWidgets.QWidget()
        self.Manual.setObjectName("Manual")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Manual)
        self.verticalLayout.setObjectName("verticalLayout")
        self.manualpage = QtWebEngineWidgets.QWebEngineView(self.Manual)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manualpage.sizePolicy().hasHeightForWidth())
        self.manualpage.setSizePolicy(sizePolicy)
        self.manualpage.setUrl(QtCore.QUrl("about:blank"))
        self.manualpage.setObjectName("manualpage")
        self.verticalLayout.addWidget(self.manualpage)
        self.commandtab.addTab(self.Manual, "")
        self.verticalLayout_3.addWidget(self.commandtab)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.commandboxlayout = QtWidgets.QHBoxLayout()
        self.commandboxlayout.setObjectName("commandboxlayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.commandboxlayout.addItem(spacerItem)
        self.closecommand = QtWidgets.QPushButton(self.groupBox)
        self.closecommand.setMinimumSize(QtCore.QSize(0, 30))
        self.closecommand.setMaximumSize(QtCore.QSize(16777215, 30))
        self.closecommand.setObjectName("closecommand")
        self.commandboxlayout.addWidget(self.closecommand)
        self.runcommand = QtWidgets.QPushButton(self.groupBox)
        self.runcommand.setMinimumSize(QtCore.QSize(0, 30))
        self.runcommand.setMaximumSize(QtCore.QSize(16777215, 30))
        self.runcommand.setObjectName("runcommand")
        self.commandboxlayout.addWidget(self.runcommand)
        self.copycommand = QtWidgets.QPushButton(self.groupBox)
        self.copycommand.setMinimumSize(QtCore.QSize(0, 30))
        self.copycommand.setMaximumSize(QtCore.QSize(16777215, 30))
        self.copycommand.setObjectName("copycommand")
        self.commandboxlayout.addWidget(self.copycommand)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.commandboxlayout.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.commandboxlayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.status = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setMinimumSize(QtCore.QSize(0, 26))
        self.status.setMaximumSize(QtCore.QSize(16777215, 26))
        self.status.setFrameShape(QtWidgets.QFrame.Box)
        self.status.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.status.setText("")
        self.status.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.status.setObjectName("status")
        self.verticalLayout_4.addWidget(self.status)

        self.retranslateUi(Form)
        self.commandtab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.commandtab.setTabText(self.commandtab.indexOf(self.CommandOutput), _translate("Form", "Command Output"))
        self.commandtab.setTabText(self.commandtab.indexOf(self.Manual), _translate("Form", "Manual"))
        self.closecommand.setText(_translate("Form", "Close"))
        self.runcommand.setText(_translate("Form", "Run"))
        self.copycommand.setText(_translate("Form", "Copy"))

from PyQt5 import QtWebEngineWidgets
import resources_rc
