# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MGT_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.2.dev1804051511
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(563, 545)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.module = QtWidgets.QWidget()
        self.module.setObjectName("module")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.module)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.commandtab = QtWidgets.QTabWidget(self.module)
        self.commandtab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.commandtab.setObjectName("commandtab")
        self.CommandOutput = QtWidgets.QWidget()
        self.CommandOutput.setObjectName("CommandOutput")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.CommandOutput)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.commandoutput = QtWidgets.QTextEdit(self.CommandOutput)
        self.commandoutput.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.commandoutput.setObjectName("commandoutput")
        self.verticalLayout_2.addWidget(self.commandoutput)
        self.commandtab.addTab(self.CommandOutput, "")
        self.Manual = QtWidgets.QWidget()
        self.Manual.setObjectName("Manual")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Manual)
        self.verticalLayout.setObjectName("verticalLayout")
        self.manualpage = QtWebEngineWidgets.QWebEngineView(self.Manual)
        self.manualpage.setUrl(QtCore.QUrl("about:blank"))
        self.manualpage.setObjectName("manualpage")
        self.verticalLayout.addWidget(self.manualpage)
        self.commandtab.addTab(self.Manual, "")
        self.verticalLayout_3.addWidget(self.commandtab)
        self.commandbox = QtWidgets.QGroupBox(self.module)
        self.commandbox.setTitle("")
        self.commandbox.setObjectName("commandbox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.commandbox)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.commandboxlayout = QtWidgets.QHBoxLayout()
        self.commandboxlayout.setObjectName("commandboxlayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.commandboxlayout.addItem(spacerItem)
        self.closecommand = QtWidgets.QPushButton(self.commandbox)
        self.closecommand.setObjectName("closecommand")
        self.commandboxlayout.addWidget(self.closecommand)
        self.runcommand = QtWidgets.QPushButton(self.commandbox)
        self.runcommand.setObjectName("runcommand")
        self.commandboxlayout.addWidget(self.runcommand)
        self.copycommand = QtWidgets.QPushButton(self.commandbox)
        self.copycommand.setObjectName("copycommand")
        self.commandboxlayout.addWidget(self.copycommand)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.commandboxlayout.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.commandboxlayout)
        self.verticalLayout_3.addWidget(self.commandbox)
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 563, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuGradient_Metrics = QtWidgets.QMenu(self.menubar)
        self.menuGradient_Metrics.setObjectName("menuGradient_Metrics")
        self.menuDirectionality = QtWidgets.QMenu(self.menuGradient_Metrics)
        self.menuDirectionality.setObjectName("menuDirectionality")
        self.menuStatistics = QtWidgets.QMenu(self.menuGradient_Metrics)
        self.menuStatistics.setObjectName("menuStatistics")
        self.menuSurface_Texture = QtWidgets.QMenu(self.menuGradient_Metrics)
        self.menuSurface_Texture.setObjectName("menuSurface_Texture")
        self.menuTemperature_and_Moisture = QtWidgets.QMenu(self.menuGradient_Metrics)
        self.menuTemperature_and_Moisture.setObjectName("menuTemperature_and_Moisture")
        self.menuUtilities = QtWidgets.QMenu(self.menuGradient_Metrics)
        self.menuUtilities.setObjectName("menuUtilities")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuZonal_Statistics = QtWidgets.QMenu(self.menubar)
        self.menuZonal_Statistics.setObjectName("menuZonal_Statistics")
        self.menuModelling = QtWidgets.QMenu(self.menubar)
        self.menuModelling.setObjectName("menuModelling")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.taskmanager = QtWidgets.QDockWidget(MainWindow)
        self.taskmanager.setObjectName("taskmanager")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.taskmanager.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.taskmanager)
        self.actionClassify_Aspect = QtWidgets.QAction(MainWindow)
        self.actionClassify_Aspect.setObjectName("actionClassify_Aspect")
        self.actionLinear_Aspect = QtWidgets.QAction(MainWindow)
        self.actionLinear_Aspect.setObjectName("actionLinear_Aspect")
        self.actionMean_Slope = QtWidgets.QAction(MainWindow)
        self.actionMean_Slope.setObjectName("actionMean_Slope")
        self.actionCorrelation = QtWidgets.QAction(MainWindow)
        self.actionCorrelation.setObjectName("actionCorrelation")
        self.actionDeviation_from_trend = QtWidgets.QAction(MainWindow)
        self.actionDeviation_from_trend.setObjectName("actionDeviation_from_trend")
        self.actionGaussian_Smoothing = QtWidgets.QAction(MainWindow)
        self.actionGaussian_Smoothing.setObjectName("actionGaussian_Smoothing")
        self.actionInvert = QtWidgets.QAction(MainWindow)
        self.actionInvert.setObjectName("actionInvert")
        self.actionLocal_deviation_from_global = QtWidgets.QAction(MainWindow)
        self.actionLocal_deviation_from_global.setObjectName("actionLocal_deviation_from_global")
        self.actionMoments = QtWidgets.QAction(MainWindow)
        self.actionMoments.setObjectName("actionMoments")
        self.actionNormal = QtWidgets.QAction(MainWindow)
        self.actionNormal.setObjectName("actionNormal")
        self.actionSlope_Impedence = QtWidgets.QAction(MainWindow)
        self.actionSlope_Impedence.setObjectName("actionSlope_Impedence")
        self.actionSobel_Gradient = QtWidgets.QAction(MainWindow)
        self.actionSobel_Gradient.setObjectName("actionSobel_Gradient")
        self.actionTransformation = QtWidgets.QAction(MainWindow)
        self.actionTransformation.setObjectName("actionTransformation")
        self.actionDissection = QtWidgets.QAction(MainWindow)
        self.actionDissection.setObjectName("actionDissection")
        self.actionLandform = QtWidgets.QAction(MainWindow)
        self.actionLandform.setObjectName("actionLandform")
        self.actionRoughness = QtWidgets.QAction(MainWindow)
        self.actionRoughness.setObjectName("actionRoughness")
        self.actionSlope_Position = QtWidgets.QAction(MainWindow)
        self.actionSlope_Position.setObjectName("actionSlope_Position")
        self.actionSurface_Area_Ratio = QtWidgets.QAction(MainWindow)
        self.actionSurface_Area_Ratio.setObjectName("actionSurface_Area_Ratio")
        self.actionSurface_Relief_Ratio = QtWidgets.QAction(MainWindow)
        self.actionSurface_Relief_Ratio.setObjectName("actionSurface_Relief_Ratio")
        self.action2nd_Derivative_Slope = QtWidgets.QAction(MainWindow)
        self.action2nd_Derivative_Slope.setObjectName("action2nd_Derivative_Slope")
        self.actionCompound_Topographic_Index = QtWidgets.QAction(MainWindow)
        self.actionCompound_Topographic_Index.setObjectName("actionCompound_Topographic_Index")
        self.actionHeat_Load_Index = QtWidgets.QAction(MainWindow)
        self.actionHeat_Load_Index.setObjectName("actionHeat_Load_Index")
        self.actionIntegrated_Moisture_Index = QtWidgets.QAction(MainWindow)
        self.actionIntegrated_Moisture_Index.setObjectName("actionIntegrated_Moisture_Index")
        self.actionSite_Exposure_Index = QtWidgets.QAction(MainWindow)
        self.actionSite_Exposure_Index.setObjectName("actionSite_Exposure_Index")
        self.actionSlope_Aspect_Transformation = QtWidgets.QAction(MainWindow)
        self.actionSlope_Aspect_Transformation.setObjectName("actionSlope_Aspect_Transformation")
        self.actionAngle_Conversion = QtWidgets.QAction(MainWindow)
        self.actionAngle_Conversion.setObjectName("actionAngle_Conversion")
        self.actionClass_Percentage = QtWidgets.QAction(MainWindow)
        self.actionClass_Percentage.setObjectName("actionClass_Percentage")
        self.actionNo_Data_Fill = QtWidgets.QAction(MainWindow)
        self.actionNo_Data_Fill.setObjectName("actionNo_Data_Fill")
        self.actionSieve = QtWidgets.QAction(MainWindow)
        self.actionSieve.setObjectName("actionSieve")
        self.actionUnsupervised_Classification = QtWidgets.QAction(MainWindow)
        self.actionUnsupervised_Classification.setObjectName("actionUnsupervised_Classification")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuDirectionality.addAction(self.actionClassify_Aspect)
        self.menuDirectionality.addAction(self.actionLinear_Aspect)
        self.menuDirectionality.addAction(self.actionMean_Slope)
        self.menuStatistics.addAction(self.actionCorrelation)
        self.menuStatistics.addAction(self.actionDeviation_from_trend)
        self.menuStatistics.addAction(self.actionGaussian_Smoothing)
        self.menuStatistics.addAction(self.actionInvert)
        self.menuStatistics.addAction(self.actionLocal_deviation_from_global)
        self.menuStatistics.addAction(self.actionMoments)
        self.menuStatistics.addAction(self.actionNormal)
        self.menuStatistics.addAction(self.actionSlope_Impedence)
        self.menuStatistics.addAction(self.actionSobel_Gradient)
        self.menuStatistics.addAction(self.actionTransformation)
        self.menuSurface_Texture.addAction(self.actionDissection)
        self.menuSurface_Texture.addAction(self.actionLandform)
        self.menuSurface_Texture.addAction(self.actionRoughness)
        self.menuSurface_Texture.addAction(self.actionSlope_Position)
        self.menuSurface_Texture.addAction(self.actionSurface_Area_Ratio)
        self.menuSurface_Texture.addAction(self.actionSurface_Relief_Ratio)
        self.menuTemperature_and_Moisture.addAction(self.action2nd_Derivative_Slope)
        self.menuTemperature_and_Moisture.addAction(self.actionCompound_Topographic_Index)
        self.menuTemperature_and_Moisture.addAction(self.actionHeat_Load_Index)
        self.menuTemperature_and_Moisture.addAction(self.actionIntegrated_Moisture_Index)
        self.menuTemperature_and_Moisture.addAction(self.actionSite_Exposure_Index)
        self.menuTemperature_and_Moisture.addAction(self.actionSlope_Aspect_Transformation)
        self.menuUtilities.addAction(self.actionAngle_Conversion)
        self.menuUtilities.addAction(self.actionClass_Percentage)
        self.menuUtilities.addAction(self.actionNo_Data_Fill)
        self.menuUtilities.addAction(self.actionSieve)
        self.menuGradient_Metrics.addAction(self.menuDirectionality.menuAction())
        self.menuGradient_Metrics.addAction(self.menuStatistics.menuAction())
        self.menuGradient_Metrics.addAction(self.menuSurface_Texture.menuAction())
        self.menuGradient_Metrics.addAction(self.menuTemperature_and_Moisture.menuAction())
        self.menuGradient_Metrics.addSeparator()
        self.menuGradient_Metrics.addAction(self.menuUtilities.menuAction())
        self.menuModelling.addAction(self.actionUnsupervised_Classification)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuGradient_Metrics.menuAction())
        self.menubar.addAction(self.menuZonal_Statistics.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuModelling.menuAction())

        self.retranslateUi(MainWindow)
        self.commandtab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MGT - Marine Geomorphometric Toolbox"))
        self.module.setWindowTitle(_translate("MainWindow", "module"))
        self.commandtab.setTabText(self.commandtab.indexOf(self.CommandOutput), _translate("MainWindow", "Command Output"))
        self.commandtab.setTabText(self.commandtab.indexOf(self.Manual), _translate("MainWindow", "Manual"))
        self.closecommand.setText(_translate("MainWindow", "Close"))
        self.runcommand.setText(_translate("MainWindow", "Run"))
        self.copycommand.setText(_translate("MainWindow", "Copy"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuGradient_Metrics.setTitle(_translate("MainWindow", "Gradient Metrics"))
        self.menuDirectionality.setTitle(_translate("MainWindow", "Directionality"))
        self.menuStatistics.setTitle(_translate("MainWindow", "Statistics"))
        self.menuSurface_Texture.setTitle(_translate("MainWindow", "Surface Texture"))
        self.menuTemperature_and_Moisture.setTitle(_translate("MainWindow", "Temperature and Moisture"))
        self.menuUtilities.setTitle(_translate("MainWindow", "Utilities"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuZonal_Statistics.setTitle(_translate("MainWindow", "Zonal Statistics"))
        self.menuModelling.setTitle(_translate("MainWindow", "Modelling"))
        self.taskmanager.setWindowTitle(_translate("MainWindow", "Task Manager"))
        self.actionClassify_Aspect.setText(_translate("MainWindow", "Classify Aspect"))
        self.actionLinear_Aspect.setText(_translate("MainWindow", "Linear Aspect"))
        self.actionMean_Slope.setText(_translate("MainWindow", "Mean Slope"))
        self.actionCorrelation.setText(_translate("MainWindow", "Correlation"))
        self.actionDeviation_from_trend.setText(_translate("MainWindow", "Deviation from Trend"))
        self.actionGaussian_Smoothing.setText(_translate("MainWindow", "Gaussian Smoothing"))
        self.actionInvert.setText(_translate("MainWindow", "Invert"))
        self.actionLocal_deviation_from_global.setText(_translate("MainWindow", "Local Deviation from Global"))
        self.actionMoments.setText(_translate("MainWindow", "Moments"))
        self.actionNormal.setText(_translate("MainWindow", "Normal"))
        self.actionSlope_Impedence.setText(_translate("MainWindow", "Slope Impedence"))
        self.actionSobel_Gradient.setText(_translate("MainWindow", "Sobel Gradient"))
        self.actionTransformation.setText(_translate("MainWindow", "Transformations"))
        self.actionDissection.setText(_translate("MainWindow", "Dissection"))
        self.actionLandform.setText(_translate("MainWindow", "Landform"))
        self.actionRoughness.setText(_translate("MainWindow", "Roughness"))
        self.actionSlope_Position.setText(_translate("MainWindow", "Slope Position"))
        self.actionSurface_Area_Ratio.setText(_translate("MainWindow", "Surface Area Ratio"))
        self.actionSurface_Relief_Ratio.setText(_translate("MainWindow", "Surface Relief Ratio"))
        self.action2nd_Derivative_Slope.setText(_translate("MainWindow", "2nd Derivative Slope"))
        self.actionCompound_Topographic_Index.setText(_translate("MainWindow", "Compound Topographic Index"))
        self.actionHeat_Load_Index.setText(_translate("MainWindow", "Heat Load Index"))
        self.actionIntegrated_Moisture_Index.setText(_translate("MainWindow", "Integrated Moisture Index"))
        self.actionSite_Exposure_Index.setText(_translate("MainWindow", "Site Exposure Index"))
        self.actionSlope_Aspect_Transformation.setText(_translate("MainWindow", "Slope Aspect Transformation"))
        self.actionAngle_Conversion.setText(_translate("MainWindow", "Angle Conversion"))
        self.actionClass_Percentage.setText(_translate("MainWindow", "Class Percentage"))
        self.actionNo_Data_Fill.setText(_translate("MainWindow", "No-Data Fill"))
        self.actionSieve.setText(_translate("MainWindow", "Sieve"))
        self.actionUnsupervised_Classification.setText(_translate("MainWindow", "Unsupervised Classification"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences..."))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

from PyQt5 import QtWebEngineWidgets
